### ISSUE TITLE
On create extension login_hook, ERROR:  catcache reference 0x7f1d28844cf0 is not owned by resource owner TopTransaction

### ISSUE THREAD

**Issue by edougf** [splendiddata/login_hook#19]
Hello, 

For some time now, two or three months, I started to notice this error, when execute "create extension login_hook":

     ERROR:  catcache reference 0x7f1d28844cf0 is not owned by resource owner TopTransaction

On 16.0 version.

What's even stranger is that, if I run it a second time, immediately afterwards, I no longer have the error and the extension is created successfully.

Could it be a bug?

Thanks

**Comment by M-Butter** [comment]
Hello,

The login_hook extension implements function _PG_init(). That function will be executed on first access of anything in the extension. And because of the "session_preload_libraries = 'login_hook'" setting, that first access will occur very early in the startup sequence of a session. That is how the extension works.

Since a resent version of Postgres, the create extension statement is considered a first access of that extension as well. So also then, the _PG_init() function is invoked. Apparently the _PG_init() function tries to read a resource that is owned by the create extension command. Postgres doesn't like that, so rolls back the subtransaction that the _PG_init() function started. That is not a problem as the function wasn't supposed to be executed at that time in the first place.

The problem occurs only when you execute the create extension login_hook the first time in a session. So normally only once in the life time of a database. Nothing really goes wrong. So consider it a caveat.

Regards,
Martin.

**Comment by edougf** [comment]
Hi , 

This could be the problem (_pg_init() ) ? because I have the extension create in the entrypoint, even though the variable is defined, the extension's create always fails

I forgot to say that I have Postgres being created in Docker


Thanks

**Comment by M-Butter** [comment]
The create extension statement does show the error message. But still the extension is created. So in the end nothing has gone wrong.

**Comment by edougf** [comment]
It's resolved! in the entrypoint, I have to create a  db session to define the variable session_preload_libraries=login_hook, and then in a new session I have to do the create extension. If I do it in the same session I always get an error

When there was an error, the extension was not created, only if you ran create extension a second time

Thank you

The issue can be closed!!
